# ==================================================
# Configuración de Conexión a Base de Datos
# ==================================================
# Apuntamos a tu contenedor Docker en Kali
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Permite crear las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==================================================
# Vulnerabilidades de Seguridad (Para tu auditoría)
# ==================================================
# OWASP A02: Fallos Criptográficos - Credenciales expuestas
app.security.jwt.secret=MI_CLAVE_SECRETA_SUPER_FACIL_DE_ADIVINAR_2026
app.security.admin.password=admin123456